---
- hosts: bind
  remote_user: root
  tasks:
    - template:
        src: files/named.conf.local
        dest: /etc/bind/named.conf.local
        #validate: /usr/sbin/sshd -t -f %s
      notify: reload bind
      
    - template:
        src: files/domain.db
        dest: "/etc/bind/zones/{{item.name}}.db"
        validate: "named-checkzone {{item.name}} %s"
      with_items: "{{ domains }}"
      notify: reload bind

  handlers:
    - name: reload bind
      service:
        name: bind9
        state: reloaded

- hosts: freeswitch
  remote_user: root
  vars:
    all_domains: []
    managed_files: []
  tasks:
    - set_fact:
        all_domains: "{{all_domains}} + [ '{{item.sip_domain}}' ]"
      with_items: "{{ domains }}"
      tags:
         - configuration
    
    - name: Find /var/log all directories, exclude nginx and mysql
      find:
        paths: /etc/freeswitch/directory
        recurse: no
        file_type: any
        excludes: 'default,default.xml'
      register: files_matched
      tags:
         - configuration
        
    - name: remove web dir contents
      file: 
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_matched.files }}"
      when: item.path | basename not in all_domains
      tags:
         - configuration
      
    
    - file: path=/etc/freeswitch/directory/{{ item.sip_domain }} state=directory
      with_items: "{{ domains }}"
      tags:
         - configuration

    - set_fact:
        managed_files:  "{{managed_files}} + /etc/freeswitch/directory/{{ item[0].sip_domain }}/{{item[1].sip_user_id}}.xml"
      with_subelements:
         - "{{ domains }}"
         - users   
      tags:
         - configuration
      
    - template:
        src: files/freeswitch/user.xml
        dest: "/etc/freeswitch/directory/{{ item[0].sip_domain }}/{{item[1].sip_user_id}}.xml"
      with_subelements:
         - "{{ domains }}"
         - users
      tags:
         - configuration
         
    - find:
        paths: "/etc/freeswitch/directory/{{ item.sip_domain }}"
        patterns: "[0-9]+.xml"
        excludes: 'default/*,default.xml'
        use_regex: yes
        recurse: yes
      register: user_files
      with_items: "{{ domains }}"
      tags:
         - configuration
        
    - name: remove unused users
      file: 
        path: "{{ item.1.path }}"
        state: absent
      with_subelements:
         - "{{ user_files.results }}"
         - files  
      when: item.1.path not in managed_files
      tags:
         - configuration
         
  handlers:
    - name: reload freeswitch
      service:
        name: freeswitch
        state: reloaded
