---
- hosts: bind
  remote_user: root
  tasks:
    - template:
        src: files/named.conf.local
        dest: /etc/bind/named.conf.local
        #validate: /usr/sbin/sshd -t -f %s
      notify: reload bind
      
    - template:
        src: files/domain.db
        dest: "/etc/bind/zones/{{item.name}}.db"
        validate: "named-checkzone {{item.name}} %s"
      with_items: "{{ domains }}"
      notify: reload bind

  handlers:
    - name: reload bind
      service:
        name: bind9
        state: reloaded

- hosts: freeswitch
  remote_user: root
  vars:
    all_domains: []
    managed_files: []
  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://files.freeswitch.org/repo/deb/freeswitch-1.8/fsstretch-archive-keyring.asc
        state: present
        
    - lineinfile:
        path: /etc/apt/sources.list.d/freeswitch.list
        regexp: '^deb'
        line: 'deb http://files.freeswitch.org/repo/deb/freeswitch-1.8/ stretch main'
        create: yes
    
    - lineinfile:
        path: /etc/freeswitch/sip_profiles/internal.xml
        regexp: '(.*)<param name="ext-rtp-ip" value=.*>'
        line: "    <param name=\"ext-rtp-ip\" value=\"{{inventory_hostname}}\"/>"
        create: yes
      tags:
        - setup
      notify: restart freeswitch
        
    - lineinfile:
        path: /etc/freeswitch/sip_profiles/internal.xml
        regexp: '(.*)<param name="ext-sip-ip" value=.*>'
        line: "    <param name=\"ext-sip-ip\" value=\"{{inventory_hostname}}\"/>"
        create: yes
      tags:
        - setup
      notify: restart freeswitch
      
    - lineinfile:
        path: /etc/freeswitch/vars.xml
        regexp: '(.*)<X-PRE-PROCESS cmd="set" data="default_password=.*'
        line: '\1<X-PRE-PROCESS cmd="set" data="default_password=12698775648954563564"/>'
        create: yes
        backrefs: yes
      tags:
        - setup
      notify: restart freeswitch
        
    - name: Update repositories cache and install "foo" package
      apt:
        name: freeswitch-meta-all
        update_cache: yes
        
    - lineinfile:
        path: /etc/freeswitch/sip_profiles/internal.xml
        state: absent
        regexp: '{{ item }}'
      with_items: 
      - force-register-domain
      - force-subscription-domain
      - force-register-db-domain
      notify: restart freeswitch

    - set_fact:
        all_domains: "{{all_domains}} + [ '{{item.sip_domain}}' ]"
      with_items: "{{ domains }}"
      tags:
         - configuration
    
    - name: Find /var/log all directories, exclude nginx and mysql
      find:
        paths: /etc/freeswitch/directory
        recurse: no
        file_type: any
        excludes: 'default,default.xml'
      register: files_matched
      tags:
         - configuration
        
    - name: remove web dir contents
      file: 
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_matched.files }}"
      when: item.path | basename not in all_domains
      tags:
         - configuration
      
    
    - file: path=/etc/freeswitch/directory/{{ item.sip_domain }} state=directory
      with_items: "{{ domains }}"
      tags:
         - configuration

    - set_fact:
        managed_files:  "{{managed_files}} + /etc/freeswitch/directory/{{ item[0].sip_domain }}/{{item[1].sip_user_id}}.xml"
      with_subelements:
         - "{{ domains }}"
         - users   
      tags:
         - configuration
         
    - set_fact:
        managed_files:  "{{managed_files}} + /etc/freeswitch/directory/{{ item[0].sip_domain }}/{{item[1].number}}.xml"
      with_subelements:
         - "{{ domains }}"
         - gsm_lines   
      tags:
         - configuration
    
    - template:
        src: files/freeswitch/domain.xml
        dest: "/etc/freeswitch/directory/{{ item.sip_domain }}.xml"
      with_items:
         - "{{ domains }}"
      tags:
         - configuration
      notify: reload freeswitch
    
    - template:
        src: files/freeswitch/user.xml
        dest: "/etc/freeswitch/directory/{{ item[0].sip_domain }}/{{item[1].sip_user_id}}.xml"
      with_subelements:
         - "{{ domains }}"
         - users
      tags:
         - configuration
      notify: reload freeswitch
      
    - template:
        src: files/freeswitch/user_goip.xml
        dest: "/etc/freeswitch/directory/{{ item[0].sip_domain }}/{{item[1].number}}.xml"
      with_subelements:
         - "{{ domains }}"
         - gsm_lines
      tags:
         - configuration
      notify: reload freeswitch
      
    - name: Setup Dialplans
      template:
        src: files/freeswitch/dialplan.xml
        dest: "/etc/freeswitch/dialplan/{{ item.sip_domain }}.xml"
      with_items:
         - "{{ domains }}"
      tags:
         - configuration
         - dialplan
      notify: reload freeswitch
         
    - find:
        paths: "/etc/freeswitch/directory/{{ item.sip_domain }}"
        patterns: "[0-9]+.xml"
        excludes: 'default/*,default.xml'
        use_regex: yes
        recurse: yes
      register: user_files
      with_items: "{{ domains }}"
      tags:
         - configuration
        
    - name: remove unused users
      file: 
        path: "{{ item.1.path }}"
        state: absent
      with_subelements:
         - "{{ user_files.results }}"
         - files  
      when: item.1.path not in managed_files
      tags:
         - configuration
         
  handlers:
    - name: reload freeswitch
      service:
        name: freeswitch
        state: restarted
    - name: restart freeswitch
      service:
        name: freeswitch
        state: restarted
