bind:
  hosts:
    10.65.35.37:
      domains:
      - a: 51.15.222.230
        name: pbx.joolfoo.com
      - a: 51.15.222.230
        name: ibeesmart.pbx.joolfoo.com
      - a: 51.15.222.230
        name: uom.pbx.joolfoo.com
freeswitch:
  hosts:
    51.15.222.230:
      domains:
      - groups: []
        sip_domain: pbx.joolfoo.com
        users: []
        gsm_lines: []
      - groups: []
        sip_domain: ibeesmart.pbx.joolfoo.com
        gsm_lines:
          - number: 59018277
            forward_to: 1000
        users:
        - sip_password: null
          sip_user_id: '1003'
        - sip_password: null
          sip_user_id: '1002'
        - sip_password: null
          sip_user_id: '1001'
        - sip_password: null
          sip_user_id: '1000'
      - groups: []
        sip_domain: uom.pbx.joolfoo.com
        users: []
        gsm_lines: []
