---
bind:
  hosts:
    10.65.35.37:
        domains:
            - name: uom.pbx.joolfoo.com
              a: '10.65.35.16'

freeswitch:
    hosts:
        10.65.35.166:
            domains:
              - sip_domain: uom.pbx.joolfoo.com
                users: 
                    - sip_user_id: 1000
                      password: 12345
                groups:
                    - sip_extension: 8000
                      users:
                        - 1000
                        - 1002
